[project]
name = "guestandgray"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12.0"
dependencies = [
    "coderedcms",
    "django-bootstrap5",
    "django-environ",
    "django-import-export",
    "django-tempus-dominus",
    "django-cookie-law",
    "django-markdownify",
    "django-htmx",
    "django-honeypot",
    "coderedcms-bootstrap4",
    "django-jazzmin",
    "psycopg",
    #    "tablib",
    "python-resize-image",
    "bcrypt",
    "django-tableaux",
    "sentry-sdk",
    "gunicorn",
    "django-tables2==2.7.5",
    "django==4.2",
]
[dependency-groups]
dev = [
    "django-upgrade==1.22.2",
    "django-sass>=1.1.0",
    "fabric==3.2.2",
    "pytest>=1.0.0",
    "django-sass",
    "django-debug-toolbar",
    ]

#[tool.uv.sources]
#django-tableaux = { path = "C:/Users/is/PycharmProjects/django_tableaux", editable = true}
