# Generated by Django 2.2.4 on 2019-08-17 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0015_coderedsessionformsubmission_coderedsubmissionrevision'),
        ('website', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CataloguePage',
            fields=[
                ('coderedpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coderedcms.CoderedPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('coderedcms.coderedpage',),
        ),
    ]
