# Generated by Django 2.2.4 on 2019-09-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0003_capitalizeverbose"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("coderedcms", "0015_coderedsessionformsubmission_coderedsubmissionrevision"),
        ("website", "0003_cataloguepage"),
    ]

    operations = [migrations.DeleteModel(name="CataloguePage")]
