# Generated by Django 3.1.6 on 2022-01-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_auto_20211227_1914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
