#!/bin/bash

# These constants can be changed by sed
NAME="XXapp"
SETTINGS="XXsettings"
VENV='XXvenv'

WORKERS=3
DIR=/home/django/$NAME
USER=django
GROUP=django
BIND=unix:/home/django/$NAME/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=mysite.settings.$SETTINGS
DJANGO_WSGI_MODULE=mysite.wsgi
LOG_LEVEL=debug

cd $DIR
source $VENV/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec $VENV/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level $LOG_LEVEL \
  --log-file=-

