# Generated by Django 2.2.4 on 2019-08-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("shop", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="section",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="shop.CustomImage",
            ),
        )
    ]
