# Generated by Django 2.2.4 on 2019-08-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shop", "0002_object_has_image")]

    operations = [
        migrations.AddField(
            model_name="object",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        )
    ]
