# Generated by Django 2.2.4 on 2019-09-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("shop", "0002_auto_20190916_1707")]

    operations = [
        migrations.AddField(
            model_name="item", name="archive", field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name="item", name="visible", field=models.BooleanField(default=True)
        ),
    ]
