# Generated by Django 2.2.4 on 2019-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shop", "0003_auto_20190916_1830")]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image_file",
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
