# Generated by Django 2.2.4 on 2019-08-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("shop", "0003_object_slug")]

    operations = [
        migrations.RemoveField(model_name="object", name="has_image"),
        migrations.AddField(
            model_name="object",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_object",
                to="shop.CustomImage",
            ),
        ),
    ]
