# Generated by Django 2.2.4 on 2019-08-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shop", "0004_auto_20190823_1430")]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
