# Generated by Django 2.2.4 on 2019-09-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("shop", "0005_auto_20190823_1614")]

    operations = [migrations.RenameModel(old_name="Category", new_name="OldCategory")]
