# Generated by Django 2.2.6 on 2019-10-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shop", "0006_address_contact_enquiry")]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="subject",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry", name="message", field=models.TextField(null=True)
        ),
    ]
