# Generated by Django 2.2.4 on 2019-09-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("shop", "0007_category")]

    operations = [
        migrations.AddField(
            model_name="object",
            name="new_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.Category",
            ),
        )
    ]
