# Generated by Django 2.2.4 on 2019-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shop", "0008_object_new_category")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", max_length=200),
            preserve_default=False,
        )
    ]
