# Generated by Django 2.2.6 on 2019-10-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shop", "0009_book")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="compiler",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="sub_title1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="sub_title2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="sub_title3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
