# Generated by Django 2.2.4 on 2019-09-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shop", "0009_category_slug")]

    operations = [
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=100)
        ),
        migrations.AlterField(
            model_name="category",
            name="short_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="category", name="slug", field=models.CharField(max_length=400)
        ),
    ]
