# Generated by Django 2.2.4 on 2019-09-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("shop", "0010_auto_20190904_0822")]

    operations = [
        migrations.RemoveField(model_name="object", name="category"),
        migrations.DeleteModel(name="OldCategory"),
    ]
