# Generated by Django 2.2.6 on 2019-10-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("shop", "0010_auto_20191015_1455")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="archive_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archive_category",
                to="shop.CustomImage",
            ),
        )
    ]
