# Generated by Django 2.2.6 on 2019-10-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shop", "0012_auto_20191018_1140")]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="subtitle",
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
