# Generated by Django 2.2.4 on 2019-09-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("shop", "0012_auto_20190910_1741")]

    operations = [
        migrations.RenameModel(old_name="Object", new_name="Item"),
        migrations.RenameField(
            model_name="customimage", old_name="object", new_name="item"
        ),
    ]
