# Generated by Django 2.2.7 on 2019-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shop", "0018_auto_20191104_0859")]

    operations = [
        migrations.CreateModel(
            name="ItemRef",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("prefix", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name="purchase",
            name="buyers_premium",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Buyer's premium",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="cost_lot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cost of lot",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Purchase date"),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Vendor's invoice number",
            ),
        ),
    ]
