# Generated by Django 2.2.8 on 2019-12-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("shop", "0020_auto_20191126_1054")]

    operations = [
        migrations.CreateModel(
            name="InvoiceCharge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.SmallIntegerField(
                        choices=[(0, "Shipping"), (1, "Insurance"), (2, "Other")],
                        default=0,
                    ),
                ),
                ("description", models.CharField(max_length=50)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.Invoice",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="lot",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cost of lot",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Lot number"
            ),
        ),
        migrations.DeleteModel(name="InvoiceExtra"),
    ]
