# Generated by Django 2.2.8 on 2019-12-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("shop", "0022_auto_20191212_1901")]

    operations = [
        migrations.RemoveField(model_name="contact", name="address"),
        migrations.RemoveField(model_name="contact", name="email"),
        migrations.RemoveField(model_name="contact", name="mobile_phone"),
        migrations.RemoveField(model_name="contact", name="work_phone"),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping", models.BooleanField(default=True)),
                ("billing", models.BooleanField(default=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=80, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.Contact"
                    ),
                ),
            ],
        ),
    ]
