# Generated by Django 2.2.8 on 2019-12-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("shop", "0023_auto_20191214_1221")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.Address",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.Address",
            ),
        ),
    ]
