# Generated by Django 2.2.8 on 2019-12-16 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("shop", "0025_auto_20191214_1751")]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="main_address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_contact",
                to="shop.Address",
            ),
        )
    ]
