# Generated by Django 2.2.8 on 2019-12-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("shop", "0027_auto_20191218_2018")]

    operations = [
        migrations.AddField(
            model_name="item",
            name="state",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Not for sale"),
                    (1, "On sale"),
                    (2, "Reserved"),
                    (3, "Sold"),
                ],
                default=0,
            ),
        )
    ]
