# Generated by Django 3.1.6 on 2021-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0030_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
