# Generated by Django 3.1.6 on 2021-03-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0034_item_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
