# Generated by Django 3.1.6 on 2021-03-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0035_category_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="position",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
