# Generated by Django 3.1.6 on 2021-04-04 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0037_auto_20210402_1839"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry",
            name="items",
        ),
        migrations.AddField(
            model_name="enquiry",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.item",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.contact",
            ),
        ),
    ]
