# Generated by Django 3.2.16 on 2022-10-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0042_og_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customimage",
            name="file_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=40
            ),
        ),
    ]
