# Generated by Django 3.2.16 on 2023-07-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_alter_customimage_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_prices', models.PositiveSmallIntegerField(choices=[(0, 'Use item settings'), (1, 'Show everywhere'), (2, 'Hide everywhere')], default=0)),
                ('contact_options', models.PositiveSmallIntegerField(choices=[(0, 'Use recaptcha'), (1, 'Use hcaptcha'), (2, 'No captcha'), (3, 'No contact email')], default=0)),
            ],
        ),
    ]
