# Generated by Django 3.2.20 on 2023-08-31 14:41

from django.db import migrations


def process_nulls(apps, schema_editor):
    Item = apps.get_model("shop", "item")
    Item.objects.filter(sale_price__isnull=True).update(sale_price=0)
    Item.objects.filter(cost_price__isnull=True).update(cost_price=0)
    Item.objects.filter(restoration_cost__isnull=True).update(restoration_cost=0)
    Item.objects.filter(minimum_price__isnull=True).update(minimum_price=0)
    for item in Item.objects.filter(sale_price__gt=0, minimum_price=0):
        item.minimum_price = item.sale_price
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0045_auto_20230827_0729"),
    ]

    operations = [
        migrations.RunPython(process_nulls),
    ]
