# Generated by Django 4.2 on 2025-10-16 18:53

from django.db import migrations, models
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0046_remove_nulls"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="price",
        ),
        migrations.AddField(
            model_name="item",
            name="library",
            field=models.SmallIntegerField(
                choices=[(0, "Stock"), (1, "Archive"), (2, "Research")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="customrendition",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
    ]
