# Generated by Django 4.2 on 2025-11-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0049_alter_item_rank_alter_item_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
    ]
