# Generated by Django 2.2.4 on 2019-10-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("shop", "0004_auto_20190917_1623")]

    operations = [
        migrations.AddField(
            model_name="category", name="count", field=models.IntegerField(default=0)
        )
    ]
