# Generated by Django 2.2.6 on 2019-10-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("shop", "0007_auto_20191011_1151")]

    operations = [
        migrations.RemoveField(model_name="customimage", name="primary_image"),
        migrations.RemoveField(model_name="customimage", name="ref"),
        migrations.AddField(
            model_name="contact", name="consent_date", field=models.DateField(null=True)
        ),
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
