# Generated by Django 2.2.6 on 2019-10-21 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("shop", "0012_auto_20191019_0947")]

    operations = [migrations.RemoveField(model_name="book", name="compiler")]
