# Generated by Django 2.2.6 on 2019-10-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("shop", "0015_auto_20191023_1514")]

    operations = [
        migrations.RemoveField(model_name="contact", name="other"),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="location",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "In stock"),
                    (1, "Auction"),
                    (2, "Not collected"),
                    (3, "At restorer"),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
