# Generated by Django 2.2.8 on 2019-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("shop", "0024_auto_20191214_1233")]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
