# Generated by Django 3.1.6 on 2021-02-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0032_auto_20210225_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.book",
            ),
        ),
    ]
