# Generated by Django 3.1.6 on 2021-03-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0033_item_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="rank",
            field=models.SmallIntegerField(default=10),
        ),
    ]
