# Generated by Django 3.1.6 on 2021-04-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0036_customimage_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="notes",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="message",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
