# Generated by Django 3.1.6 on 2021-08-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0040_hostpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="seo_description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="seo_description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
