# Generated by Django 4.2 on 2025-10-16 18:58

from django.db import migrations


def process_archive_flag(apps, schema_editor):
    Item = apps.get_model("shop", "Item")
    for item in Item.objects.filter(archive=True):
        item.library = 1  # archive
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0047_remove_item_price_item_library_and_more"),
    ]

    operations = [
        migrations.RunPython(process_archive_flag),
    ]
