# Generated by Django 4.2 on 2025-10-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0048_update_library"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="rank",
            field=models.SmallIntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="state",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "Not for sale"),
                    (1, "On sale"),
                    (2, "Reserved"),
                    (3, "Sold"),
                ],
                default=0,
            ),
        ),
    ]
